import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions) 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Link href='/'>home</Link>
          <Link href='/list'>List</Link>

          { session ? 
          <div><span>{session.user.name}</span><LogoutBtn/></div>
           :
           <div>
          <span>please login first </span><LoginBtn />
          </div>
          }
          </div>
        {children}
      </body>
    </html>
  );
}
