import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased border h-screen flex flex-col items-center`}
      >
        <div className="flex flex-col h-full border-2 w-[393px]">
          <div className="navbar">
            <img src="./logo7.png" alt="logo" className="h-10" />
          </div>
          <div className="main">
            {children}
          </div>
          <div className="footer">
            <Link href='/'>메인</Link>
            <p>|</p>
            <Link href='/map'>지도</Link>
            <p>|</p>
            <Link href='/record'>남은기간</Link>
          </div>
        </div>
      </body>
    </html>
  );
}
