import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from 'next/headers'
import Darkmode from "./Darkmode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let res = cookies().get('mode')
  console.log('res', res)

  let session = await getServerSession(authOptions)
  console.log('session',session)
  return (
    <html lang="en">
      <body className={ res != undefined && res.value == 'dark' ? 'dark-mode' : ''}>
        <div className="navbar">
          <Link href='/' className="logo">sonforum</Link>
          <Link href='/list'>List</Link>
          {
            session != null ? <p style={{color:'white'}}>{session.user.name}</p> : <p style={{color: 'white'}}>login first</p>
          }
          <LoginBtn />
          <Darkmode />
        </div>
        {children}</body>
    </html>
  );
}
